name: Amey Kamat
description: Official Website of Amey Kamat
author: Amey Kamat
author_email: ask5332@gmail.com
category_dir: /
baseurl:
url: http://ameykamat.github.io/
markdown: kramdown
excerpt_separator: <!--excerpt-->
gems: [jekyll-paginate]
permalink: /blog/:year/:month/:day/:title/
paginate: 1
paginate_path: "/blog/page:num/"
exclude: [README.md]
