title: Amey Kamat - Programmer and Developer
description: Amey Kamat is a Computer Engineer and Programmer based in Ponda, Goa, India. He works in the field of Artificial Intelligence, Software Engineering and Web Development
author: Amey Kamat
copyright: © Amey Kamat, 2017
author_email: amey@ameykamat.in
author_sec_email: kamat.amey@outlook.com
author_linkedin: http://linkedin.ameykamat.in
author_facebook: http://facebook.ameykamat.in
author_twitter: http://twitter.ameykamat.in
author_gplus: http://gplus.ameykamat.in
author_goodreads: http://goodreads.ameykamat.in
author_github: http://github.ameykamat.in
author_bitbucket: http://bitbucket.ameykamat.in
category_dir: /
url: http://www.ameykamat.in/
markdown: kramdown
excerpt_separator: <!--excerpt-->
gems: [jekyll-paginate, jekyll-sitemap]
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"
exclude: [README.md]
